language: php

php:
  - 7.1.3

services:
  - mysql

before_script:
- php artisan cache:clear
- php artisan config:cache
- cp .env.example .env
- composer self-update
- composer install --no-interaction
- mysql -e 'create database laravue;' -u root
- php artisan key:generate
- php artisan migrate
- npm install

script:
  - vendor/bin/phpunit
  - npm run production

notifications:
  email: false
